CREATE TABLE
    IF NOT EXISTS routine (
        routineID BIGINTINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
        createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
        day TEXT NOT NULL,
        CONSTRAINT categoryID FOREIGN KEY (categoryID) REFERENCES qbrzgvzv_ahaliyasdeensquare.product_categories (categoryID) ON DELETE CASCADE ON UPDATE CASCADE,
        CONSTRAINT vendorID FOREIGN KEY (vendorID) REFERENCES qbrzgvzv_ahaliyasdeensquare.vendor_details (vendorID) ON DELETE CASCADE ON UPDATE CASCADE
    ) AUTO_INCREMENT = 10000 DEFAULT CHARSET = UTF8MB4 COLLATE = UTF8MB4_UNICODE_CI;