export interface translateInterface {
    "home": string,
    "wishlist": string,
    "cart": string,
    "profile": string,
    "account_information": string,
    "notifications": string,
    "my_orders": string,
    "my_carts": string,
    "my_wishlists": string,
    "shipping_address": string,
    "support_tickets": string,
    "my_profile": string,
    "settings": string,
    "log_out": string,
    "name": string,
    "email": string,
    "balance": string,
    "birthday": string,
    "country": string,
    "default_shipping_address": string,
    "gender": string,
    "is_block": string,
    "last_login": string,
    "phone": string,
    "registered": string,
    "reward_coins": string,
    "user_id": string,
    "user_type": string,
    "change_language": string,
    "details": string,
    "tracking_number": string,
    "total_amount": string,
    "buy_now": string,
    "courier_address": string,
    "default_address": string,


    "notes": string,
    "routine": string,
    "monday": string,
    "tuesday": string,
    "wednesday": string,
    "thursday": string,
    "friday": string,
    "saturday": string,
    "sunday": string,
    "not_found": string,
    "income_expenditure": string,
    "expenditure": string,
    "income": string,
    "savings": string,
    "current_income_expenditure": string,
    "income_expenditure_history": string,
    "about_apps": string,


    "january": string,
    "february": string,
    "march": string,
    "april": string,
    "may": string,
    "june": string,
    "july": string,
    "august": string,
    "september": string,
    "october": string,
    "november": string,
    "december": string,
}

export const translate = {
    "bn": {
        "home": "বাড়ি",
        "wishlist": "ইচ্ছে তালিকা",
        "cart": "কার্ট",
        "profile": "প্রোফাইল",
        "account_information": "অ্যাকাউন্ট তথ্য",
        "notifications": "নোটিফিকেশন",
        "my_orders": "আমার অর্ডার",
        "my_carts": "আমার কার্ট",
        "my_wishlists": "আমার ইচ্ছে তালিকা",
        "shipping_address": "শিপিং অ্যাড্রেস",
        "support_tickets": "সাপোর্ট টিকেট",
        "my_profile": "আমার প্রোফাইল",
        "settings": "সেটিংস",
        "log_out": "লগ আউট",
        "name": "নাম",
        "email": "ইমেইল",
        "balance": "ভারসাম্য",
        "birthday": "জন্মদিন",
        "country": "দেশ",
        "default_shipping_address": "ডিফল্ট শিপিং ঠিকানা",
        "gender": "লিঙ্গ",
        "is_block": "is_block",
        "last_login": "শেষ লগইন",
        "phone": "ফোন",
        "registered": "নিবন্ধিত",
        "reward_coins": "reward_coins",
        "user_id": "ব্যবহারকারী আইডি",
        "user_type": "ব্যবহারকারীর ধরন",
        "change_language": "ভাষা পরিবর্তন করুন",
        "details": "বিস্তারিত",
        "tracking_number": "ট্র্যাকিং নম্বর",
        "total_amount": "মোট পরিমাণ",
        "buy_now": "এখন কিনুন",
        "courier_address": "কুরিয়ার ঠিকানা",
        "default_address": "ডিফল্ট",


        "notes": "নোটস",
        "routine": "রুটিন",
        "monday": "সোমবার",
        "tuesday": "মঙ্গলবার",
        "wednesday": "বুধবার",
        "thursday": "বৃহস্পতিবার",
        "friday": "শুক্রবার",
        "saturday": "শনিবার",
        "sunday": "রবিবার",
        "not_found": "খুজে পাওয়া যায় নি",
        "income_expenditure": "আয় ব্যয়",
        "income": "আয়",
        "expenditure": "ব্যয়",
        "savings": "সঞ্চয়",
        "current_income_expenditure": "বর্তমান আয় ব্যয়",
        "income_expenditure_history": "আয় ব্যয়ের ইতিহাস",
        "about_apps": "অ্যাপস সম্পর্কে",

        "january": "জানুয়ারী",
        "february": "ফেব্রুয়ারী",
        "march": "মার্চ",
        "april": "এপ্রিল",
        "may": "মে",
        "june": "জুন",
        "july": "জুলাই",
        "august": "আগস্ট",
        "september": "সেপ্টেম্বর",
        "october": "অক্টোবর",
        "november": "নভেম্বর",
        "december": "ডিসেম্বর",
    },

    "en": {
        "home": "Home",
        "wishlist": "Wishlist",
        "cart": "Cart",
        "profile": "Profile",
        "account_information": "Account Information",
        "notifications": "Notifications",
        "my_orders": "My Orders",
        "my_carts": "My Carts",
        "my_wishlists": "My Wishlists",
        "shipping_address": "Shipping Address",
        "support_tickets": "Support Tickets",
        "my_profile": "My Profile",
        "settings": "Settings",
        "log_out": "Log out",
        "name": "Name",
        "email": "Email",
        "balance": "Balance",
        "birthday": "Birthday",
        "country": "Country",
        "default_shipping_address": "default_shipping_address",
        "gender": "Gender",
        "is_block": "is_block",
        "last_login": "last_login",
        "phone": "Phone",
        "registered": "Registered",
        "reward_coins": "Reward_coins",
        "user_id": "User_id",
        "user_type": "user_type",
        "change_language": "Change Language",

        "details": "Details",
        "tracking_number": "Tracking Number",
        "total_amount": "Total Amount",
        "buy_now": "Buy Now",
        "courier_address": "Courier Address",
        "default_address": "Default",



        "notes": "Notes",
        "routine": "Routine",
        "monday": "Monday",
        "tuesday": "Tuesday",
        "wednesday": "Wednesday",
        "thursday": "Thursday",
        "friday": "Friday",
        "saturday": "Saturday",
        "sunday": "Sunday",
        "not_found": "Not Found",
        "income_expenditure": "Income Expenditure",
        "income": "Income",
        "expenditure": "Expenditure",
        "savings": "Savings",
        "current_income_expenditure": "Cur Income Expenditure",
        "income_expenditure_history": "Income Expenditure History",
        "about_apps": "About",

        "january": "January",
        "february": "February",
        "march": "March",
        "april": "April",
        "may": "May",
        "june": "June",
        "july": "July",
        "august": "August",
        "september": "September",
        "october": "October",
        "november": "November",
        "december": "December",
    }
}