export const assets_images = {
    "search_dark": require('./images/search_dark.png'),
    "search_white": require('./images/search_light.png'),
    "arrow_right_dark": require('./images/arrow_right_dark.png'),
    "arrow_right_light": require('./images/arrow_right_light.png'),
    "arrow_right_grey": require('./images/arrow_right_grey.png'),
    "home_light": require('./images/home_light.png'),
    "home_dark": require('./images/home_dark.png'),
    "wishlist_light": require('./images/favorite_light.png'),
    "wishlist_dark": require('./images/favorite_dark.png'),
    "cart_light": require('./images/cart_light.png'),
    "cart_dark": require('./images/cart_dark.png'),
    "profile_light": require('./images/profile_light.png'),
    "profile_dark": require('./images/profile_dark.png'),
    "order_light": require('./images/order_light.png'),
    "order_dark": require('./images/order_dark.png'),
    "shipping_address_dark": require('./images/shipping_address_dark.png'),
    "shipping_address_light": require('./images/shipping_address_light.png'),
    "support_ticket_dark": require('./images/support_ticket_dark.png'),
    "support_ticket_light": require('./images/support_ticket_light.png'),
    "log_out_dark": require('./images/log_out_dark.png'),
    "log_out_light": require('./images/log_out_light.png'),
    "settings_light": require('./images/settings_light.png'),
    "settings_dark": require('./images/settings_dark.png'),
    "language_light": require('./images/language_light.png'),
    "language_dark": require('./images/language_dark.png'),
    "info_dark": require('./images/info_dark.png'),
    "info_light": require('./images/info_light.png'),


    "notes_color": require('./images/routine/notes.png'),
    "routine_color": require('./images/routine/routine.png'),
    "calendar_color": require('./images/routine/calendar.png'),
}